[package]
name = "g5k-worker"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
libaegis = { path = "../aegis/libaegis", features = ["std"] }
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
memmap2 = "0.9"
raw-cpuid = "11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "3", features = ["json", "rustls", "gzip"] }

[profile.release]
opt-level = 3
lto = true
strip = true
